# Generated by Django 3.2 on 2022-07-07 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220612_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='spotify_access_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='spotify_refresh_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
